import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import ToasterComponent from "./toaster";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
  title: "Student Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <ToasterComponent />
          <div className="flex">
            {session && <Sidebar />}
            <div className="w-full h-full">
              {session && <Navbar session={session?.user?.user} />}

              <div className="p-6 grow">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
